import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer";

//header data
const headerData = {
  logoUrl:
    "https://eu-images.contentstack.com/v3/assets/blt9f7fb6656f851a15/blt8a97457bf1717a75/685a6b42a9b0909ce3b7329e/logo.jpg",
  navigationMenu: [
    {
      label: "Home",
      href: "/",
      openInNewTab: false,
    },
    {
      label: "Product",
      href: "/product",
      openInNewTab: false,
    },
    {
      label: "About",
      href: "/about-us",
      openInNewTab: false,
    },
    {
      label: "Contact",
      href: "/contact",
      openInNewTab: false,
    },
  ],
  showAnnouncement: false,
  announcementText: "",
};


//footer data
const footerData = {
  logoUrl:
    "https://eu-images.contentstack.com/v3/assets/blt9f7fb6656f851a15/blt8a97457bf1717a75/685a6b42a9b0909ce3b7329e/logo.jpg",
  navigationLinks: [
    {
      title: "Contact",
      href: "/contact",
      openInNewTab: false,
    },
    
    {
      title: "About",
      href: "/about-us",
      openInNewTab: false,
    },
  
  ],
  socialMediaLinks: [
    { platform: "Instagram", url: "https://instagram.com/yourpage" },
    { platform: "LinkedIn", url: "https://linkedin.com/in/yourprofile" },
  ],
  copyright: "© 2025 Your Company Name. All rights reserved.",
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Header {...headerData} />
        {children}
        <Footer {...footerData} />
      </body>
    </html>
  );
}
